from __future__ import annotations

import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List

from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials

from config.settings import settings
from config.logging import get_logger

logger = get_logger(__name__)

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


class GmailNotifier:
    def __init__(self, service=None) -> None:
        self._service = service  # injected in tests; built lazily in prod

    def _get_service(self):
        if self._service:
            return self._service
        from google.auth.transport.requests import Request
        from google_auth_oauthlib.flow import InstalledAppFlow
        import os

        creds: Credentials | None = None
        token_file = "token.json"
        credentials_file = "credentials.json"

        if os.path.exists(token_file):
            creds = Credentials.from_authorized_user_file(token_file, SCOPES)
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(credentials_file, SCOPES)
                creds = flow.run_local_server(port=0)
            with open(token_file, "w") as f:
                f.write(creds.to_json())

        self._service = build("gmail", "v1", credentials=creds)
        return self._service

    def send_summary(self, post_titles: List[str], dashboard_url: str = "") -> bool:
        to_addr = settings.google.gmail_notify_address
        if not to_addr:
            logger.warning("GmailNotifier: GMAIL_NOTIFY_ADDRESS not set, skipping email")
            return False

        subject = f"EduBot: {len(post_titles)} new posts ready for review"
        html_body = self._build_html(post_titles, dashboard_url)

        try:
            service = self._get_service()
            message = MIMEMultipart("alternative")
            message["To"] = to_addr
            message["Subject"] = subject
            message.attach(MIMEText(html_body, "html"))

            raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
            service.users().messages().send(
                userId="me", body={"raw": raw}
            ).execute()
            logger.info("GmailNotifier: sent summary to %s", to_addr)
            return True
        except Exception as exc:
            logger.error("GmailNotifier: failed to send email: %s", exc)
            return False

    def _build_html(self, titles: List[str], dashboard_url: str) -> str:
        items = "".join(f"<li style='margin:6px 0'>{t}</li>" for t in titles)
        review_button = (
            f'<p style="margin-top:24px">'
            f'<a href="{dashboard_url}" style="background:#10b981;color:#fff;'
            f'padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600">'
            f'Review now →</a></p>'
        ) if dashboard_url else ""

        return f"""
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px">
          <h2 style="color:#10b981">EduBot Weekly Run Complete</h2>
          <p>{len(titles)} post(s) are waiting for your review:</p>
          <ul style="padding-left:20px">{items}</ul>
          {review_button}
          <p style="color:#6b7280;font-size:12px;margin-top:32px">
            Generated by EduBot — automated IB/IGCSE content pipeline
          </p>
        </div>
        """
